Update method
ArtCode-Kazan/DataStorageProject pull request #11
Opened 2022-11-22 11:40 UTC by RoostiqueTheMan

2022-11-23 06:12 UTC, MikkoArtik requested changes
жду правки

2022-11-23 17:45 UTC, MikkoArtik requested changes
в ревью есть вопросы. Просьба на них ответить прямо в github. На будущее - если видишь, что задан вопрос - пиши на него ответ. Пригодится еще

2022-11-23 17:45 UTC, MikkoArtik commented on dbase-api-server/dbase_api_server/dbase.py
> +        work_list = []
тогда лучше works_list

2022-11-23 17:45 UTC, MikkoArtik commented on dbase-api-server/dbase_api_server/dbase.py
> +        for record in records:
records лишнее, можно обойти без объявления отдельной переменной

2022-11-23 17:45 UTC, MikkoArtik commented on dbase-api-server/main.py
> +    work_info = dbase_adapter.get_works_info(deposit.area_name)
тоже works_info

2022-11-23 17:45 UTC, MikkoArtik commented on dbase-api-server/tests/test_dbase.py
> +            ('deposit_id', second_deposit_id)
у тебя метод возвращает список объектов WorkInfo, а проверяешь почему-то список списков кортежей. Почему так?

2022-11-23 17:45 UTC, MikkoArtik commented on dbase-api-server/tests/test_main.py
> +                ['deposit_id', area_id],
почему такая организация, а не словарь?

2022-11-28 05:51 UTC, RoostiqueTheMan commented on dbase-api-server/tests/test_dbase.py
> +            ('deposit_id', second_deposit_id)
WorkInfo в таком формате возвращает данные

2022-11-28 05:52 UTC, RoostiqueTheMan commented on dbase-api-server/tests/test_main.py
> +                ['deposit_id', area_id],
WorkInfo в таком формате возвращает данные, не в формате словаря

2022-11-28 06:15 UTC, MikkoArtik requested changes
Жду новые правки

2022-11-28 06:15 UTC, MikkoArtik commented on dbase-api-server/dbase_api_server/dbase.py
> +    def get_works_info(self, area_name: str) -> Union[None, list]:
Для чего возврат None предусмотрен?

2022-11-28 06:15 UTC, MikkoArtik commented on dbase-api-server/tests/test_main.py
> +                ['deposit_id', area_id],
> WorkInfo в таком формате возвращает данные, не в формате словаря

А есть возможность возврата в виде словарая? Если нет, то скинь ссылку, где об этом написано, пож-та. Думаю, такая возможность предусмотрена

2022-11-28 08:00 UTC, MikkoArtik requested changes
Жду новых правок

2022-11-28 08:00 UTC, MikkoArtik commented on dbase-api-server/tests/test_main.py
> +    response = requests.post(url, json=payload.dict())
пусть все-таки get запросом будет им, а не post. Неверно мы решили изначально. Давай подправим

2022-11-28 11:45 UTC, MikkoArtik requested changes
Жду новые правки

2022-11-28 12:14 UTC, MikkoArtik requested changes
Жду новые правки

2022-11-28 12:14 UTC, MikkoArtik commented on dbase-api-server/dbase_api_server/dbase.py
> +            ).dict()
зачем преобразование сделано?

2022-11-28 12:14 UTC, MikkoArtik commented on dbase-api-server/main.py
> +def get_works_info(area_id: int) -> dict:
А можно ли вместо dict возвращать pydantic модель Response?

2022-11-28 12:14 UTC, MikkoArtik commented on dbase-api-server/tests/test_main.py
> +    up_test_dbase.add_work_info(second_work_info)
копипаста. Нужно упрощать код. Выносить в отдельные функции повторяющиеся участки

2022-11-28 16:36 UTC, MikkoArtik requested changes
Жду новые правки правки

2022-11-28 16:36 UTC, MikkoArtik commented on dbase-api-server/main.py
> +    return returning_info
типизиацию возвращаемого значения не исправил

2022-11-28 16:36 UTC, MikkoArtik commented on dbase-api-server/main.py
> +    return returning_info
типизиацию возвращаемого значения не исправил

2022-11-28 16:36 UTC, MikkoArtik commented on dbase-api-server/main.py
> +    return returning_info
типизиацию возвращаемого значения не исправил

2022-11-28 16:36 UTC, MikkoArtik commented on dbase-api-server/main.py
> +    return returning_info
типизиацию возвращаемого значения не исправил

2022-11-29 06:17 UTC, RoostiqueTheMan commented on dbase-api-server/tests/test_main.py
> -    response = requests.post(url, json=payload)
url и response? чтоб переменная не использовалась до ее объявления

2022-11-29 06:23 UTC, MikkoArtik requested changes
Жду новые правки

2022-11-29 06:23 UTC, MikkoArtik commented on dbase-api-server/main.py
> +    return returning_info
Да не то. Все правильно в return было.
Написано ранее, что функция не тот тип возвращает

2022-11-29 06:23 UTC, MikkoArtik commented on dbase-api-server/tests/test_main.py
> +    up_test_dbase.add_deposit_info(area_name)
Вообще не то сделал. Нет именованных аргументов в функции

2022-11-29 06:48 UTC, MikkoArtik requested changes
Жду новые правки

2022-11-29 06:48 UTC, MikkoArtik commented on dbase-api-server/tests/test_main.py
> +    area_name = 'test-area'
Зачем такая избыточность? Убери лишнюю переменную

2022-11-29 06:48 UTC, MikkoArtik commented on dbase-api-server/tests/test_main.py
> +    up_test_dbase.add_deposit_info(area_name)
Нет именованных аргументов

2022-11-29 06:48 UTC, MikkoArtik commented on dbase-api-server/tests/test_main.py
> +    first_well_name = 'test-name'
Убери эти переменные. Зачем они нужны, когда ты значения можешь сразу указать

2022-11-29 07:51 UTC, MikkoArtik approved these changes
Все получилось очень красиво. Принимается. Можешь множить, а ветку удалять

2022-11-29 07:52 UTC, merged