Postgres
ArtCode-Kazan/DataStorageProject pull request #2
Opened 2022-10-11 11:49 UTC by RoostiqueTheMan

2022-10-11 12:20 UTC, MikkoArtik requested changes
Готово. Основная проблема пока - это property и setter

2022-10-11 12:20 UTC, MikkoArtik commented on Makefile
> +ROOT = /home/sigma-st-6/Temp
лучше назвать TEMP_ROOT, так понятно, что за путь

2022-10-11 12:20 UTC, MikkoArtik commented on dbase-api-server/dbase_api_server/dbase.py
> +        self.__connection = psycopg2.connect(user=user,
не стоит так писать, лучше так:
...connect(
    user=user,
    password=password, 
   ....
)

2022-10-11 12:20 UTC, MikkoArtik commented on dbase-api-server/dbase_api_server/dbase.py
> +    def connection_value(self) -> None:
1. Неверное название property. Зaчем приписка value? Просто connection.
2. Разве тип будет None? Исправь возвращаемый тип

2022-10-11 12:20 UTC, MikkoArtik commented on dbase-api-server/dbase_api_server/dbase.py
> +    def connection_value_setup(self, new_value: None) -> None:
неверно назван тип. Изучи как правильно пользоваться property и setter. Без этого дальше работать будет просто невозможно

2022-10-11 12:20 UTC, MikkoArtik commented on dbase-api-server/pyproject.toml
> +flake8-annotations = "^2.9.1"
зачем ты это добавил через poetry? Оно должо было быть добавлено через  pip в проект, а не в пакет. Исправь

2022-10-11 12:20 UTC, MikkoArtik commented on postgres-server/Dockerfile
> +COPY . /docker-entrypoint-initdb.d/
в конце файла должна быть пустая строка. Ее нет сейчас

2022-10-11 12:20 UTC, MikkoArtik commented on postgres-server/postgres.sql
> +);
в конце должна быть пустая строка

2022-10-11 13:49 UTC, RoostiqueTheMan commented on dbase-api-server/dbase_api_server/dbase.py
> +        self.__connection = psycopg2.connect(user=user,
такой вариант не пропускает flake8, при таком варианте он допускает только один отступ

2022-10-11 13:51 UTC, RoostiqueTheMan commented on dbase-api-server/dbase_api_server/dbase.py
> +    def connection_value(self) -> None:
не смог оставить название connection, потому что тип возвращаемых данных - это объект connection, в итоге неправильно определяется

2022-10-11 14:18 UTC, MikkoArtik requested changes
prop и getter почини

2022-10-11 14:18 UTC, MikkoArtik commented on dbase-api-server/dbase_api_server/dbase.py
> +    def connection_value_setup(self, new_value: connection) -> connection:
опять неверно назван setter. Не разобрался

2022-10-11 14:27 UTC, RoostiqueTheMan commented on dbase-api-server/dbase_api_server/dbase.py
> +    def connection_value(self) -> None:
![Снимок экрана от 2022-10-11 17-26-01](https://user-images.githubusercontent.com/99748735/195118762-370ff804-b69c-43d0-a380-cb6bbd148f22.png)

2022-10-11 14:27 UTC, RoostiqueTheMan commented on dbase-api-server/dbase_api_server/dbase.py
> +        self.__connection = psycopg2.connect(user=user,
![Снимок экрана от 2022-10-11 17-26-01](https://user-images.githubusercontent.com/99748735/195118852-2043f10b-8c5b-4339-8df1-36df054f539b.png)

2022-10-11 14:29 UTC, RoostiqueTheMan commented on dbase-api-server/dbase_api_server/dbase.py
> +    def connection_value(self) -> None:
![Снимок экрана от 2022-10-11 17-28-10](https://user-images.githubusercontent.com/99748735/195119146-b838ca19-9e78-4325-944e-c595df0af659.png)

2022-10-11 14:40 UTC, RoostiqueTheMan commented on dbase-api-server/dbase_api_server/dbase.py
> +    def connection_value(self) -> None:
в аннотации типов connection.setter "connection" подсвечивается, как метод

2022-10-11 15:13 UTC, MikkoArtik requested changes
Не убрал лишние зависимости из poerty.
Не разобрался с prop и setter

2022-10-11 15:13 UTC, MikkoArtik commented on dbase-api-server/dbase_api_server/dbase.py
> +        self.__connection = psycopg2.connect(user=user,
Покажи, как ты написал, когда возникли эти ошибки

2022-10-11 15:13 UTC, MikkoArtik commented on dbase-api-server/dbase_api_server/dbase.py
> +    def connection_value(self) -> None:
> в аннотации типов connection.setter "connection" подсвечивается, как метод

А ты попробуй поработать с классом. Есть ли ошибки?
В PyCharm все норм

2022-10-11 15:13 UTC, MikkoArtik commented on dbase-api-server/dbase_api_server/dbase.py
> +        except (Exception, Error):
Не нравится, что используются общие классы исключений. Замени на конкретные исключения, которые могут возникнуть

2022-10-11 15:13 UTC, MikkoArtik commented on .gitignore
> +venv/
Нет пустой строки в конце

2022-10-11 15:22 UTC, MikkoArtik reviewed
Добавил правки по поводу typehint с None

2022-10-11 15:22 UTC, MikkoArtik commented on dbase-api-server/dbase_api_server/dbase.py
> +                 ) -> None:
Убери все возвращаемые None. Нужно уменьшить агресивность flake.
В файле .flake8 замени строку с ignore на эту:
ignore = ANN101, ANN200. Должно пропустить. Посмотри, что это значит и для чего это используется

2022-10-12 06:12 UTC, RoostiqueTheMan commented on dbase-api-server/dbase_api_server/dbase.py
> +        self.__connection = psycopg2.connect(user=user,
![Снимок экрана от 2022-10-12 09-11-37](https://user-images.githubusercontent.com/99748735/195263944-63f3f4be-718d-41e8-9488-146402ade3b1.png)

2022-10-12 06:46 UTC, MikkoArtik commented on dbase-api-server/dbase_api_server/dbase.py
> +        self.__connection = psycopg2.connect(user=user,
> ![Снимок экрана от 2022-10-12 09-11-37](https://user-images.githubusercontent.com/99748735/195263944-63f3f4be-718d-41e8-9488-146402ade3b1.png)

Тогда давай так перепишем:
``` Python
self.__connection = psycopg2.connect(
    host=host, port=port, database=database,
    user=user, password=password
)
```

2022-10-12 08:14 UTC, MikkoArtik requested changes
Ревью продолжается

2022-10-12 08:14 UTC, MikkoArtik commented on dbase-api-server/dbase_api_server/dbase.py
> +            return print(f'{error}: problems with database')
зачем убрал возврат False? У тебя типзация не совпадает теперь

2022-10-12 08:14 UTC, MikkoArtik commented on dbase-api-server/dbase_api_server/dbase.py
> +from psycopg2 import connection
сделай импорт всех типов ошибок для psycopg2

2022-10-12 08:14 UTC, MikkoArtik commented on dbase-api-server/dbase_api_server/dbase.py
> +    @connection.setter
вопрос: а зачем тебе setter здесь? Для чего ты его добавил?

2022-10-12 08:14 UTC, MikkoArtik commented on dbase-api-server/dbase_api_server/dbase.py
> +            return print(f'{error}: problems with database')
то же замечание

2022-10-12 08:14 UTC, MikkoArtik commented on dbase-api-server/dbase_api_server/dbase.py
>      def add_deposit_info(self,
почитай про принцип DRY и примени его

2022-10-12 13:27 UTC, MikkoArtik requested changes
Уже намного лучше! DRY нашел как применить, молодец.
Идем дальше. Читай заметки

2022-10-12 13:27 UTC, MikkoArtik commented on dbase-api-server/dbase_api_server/dbase.py
> +        return False
Да, это хорошее решение

2022-10-12 13:27 UTC, MikkoArtik commented on dbase-api-server/dbase_api_server/dbase.py
> +            print(f'{error}: problems with database')
для вывода сообщений  в консоль, давай лучше использовать библиотеку logger. Сдалай через нее

2022-10-12 14:01 UTC, MikkoArtik requested changes
Стало лучше. Есть пара моментов для доработки

2022-10-12 14:01 UTC, MikkoArtik commented on dbase-api-server/dbase_api_server/dbase.py
> +from psycopg2 import InternalError, ProgrammingError, DatabaseError
отдели пустой строкой модули, которые встроены в Python по умолчанию, и модули, которые установлены вручную.
плю отдели импорт исключений и connection

2022-10-12 14:01 UTC, MikkoArtik commented on dbase-api-server/dbase_api_server/dbase.py
> +                 database: str
для того, чтобы избежать такого большого кол-ва параметров идеально подходит dataclass. Используй его

2022-10-13 07:53 UTC, MikkoArtik requested changes
Накрутил с logger-ом и dataclasses. Внутри вопросы есть, жду на них ответа

2022-10-13 07:53 UTC, MikkoArtik commented on service/logger_config.py
> +)
Почему такое решение? Поясни.
Как ты планировал хранить файл логгера. А если он будет расти очень быстро по объему? Представь, что нагрузка будет очень большой на сервер.

2022-10-13 07:53 UTC, MikkoArtik commented on dbase-api-server/dbase_api_server/dbase.py
> +import psycopg2
зачем этот импорт?

2022-10-13 07:53 UTC, MikkoArtik commented on dbase-api-server/dbase_api_server/dbase.py
> +logger.addHandler(handler)
тот же вопрос, что и в модуле service

2022-10-13 07:53 UTC, MikkoArtik commented on dbase-api-server/dbase_api_server/dbase.py
> +class DepositsDatabase:
чего тут накрутил с датаклассами? Зачем?

2022-10-13 07:53 UTC, MikkoArtik commented on dbase-api-server/dbase_api_server/dbase.py
> +    def __post_init__(self):
верни как было

2022-10-13 07:53 UTC, MikkoArtik commented on dbase-api-server/dbase_api_server/dbase.py
> +    database: str
датакласс нужен для упаковки этих параметров

2022-10-13 07:53 UTC, MikkoArtik commented on dbase-api-server/dbase_api_server/dbase.py
> +from psycopg2 import connection
перемести этот импорт перед импортом ошибок

2022-10-13 07:53 UTC, MikkoArtik commented on dbase-api-server/dbase_api_server/dbase.py
> +class DepositsDatabase:
И переименуй класс  на StorageDBase. Тут явное несовпадение того, что в БД и того, как назван класс БД

2022-10-13 07:53 UTC, MikkoArtik commented on dbase-api-server/dbase_api_server/dbase.py
> +    def __commit_db_changes(self) -> bool:
можно просто назвать commit

2022-10-13 08:08 UTC, RoostiqueTheMan commented on service/logger_config.py
> +)
если заменить filemode на w? тогда логи будут перезаписываться, не будет проблем с занимаемым объемом

2022-10-13 08:10 UTC, RoostiqueTheMan commented on dbase-api-server/dbase_api_server/dbase.py
> +logger.addHandler(handler)
да, тут тоже избыточно памяти под хранение выделил, понял

2022-10-13 08:26 UTC, RoostiqueTheMan commented on dbase-api-server/dbase_api_server/dbase.py
> +import psycopg2
для self.__connection = psycopg2.connect. без импорта не сделать конект

2022-10-13 12:39 UTC, MikkoArtik requested changes
Почти все готово. См. правки

2022-10-13 12:39 UTC, MikkoArtik commented on dbase-api-server/dbase_api_server/dbase.py
> +class DBaseConnection:
да, верно. Только это должно лежать в модуле containers

2022-10-13 13:23 UTC, merged